name: knocky_edge
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.sdev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.8+61

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  dio: ^3.0.9
  json_annotation: ^3.0.1
  dynamic_theme: ^1.0.1
  scoped_model: ^1.0.1
  after_layout: ^1.0.7+1
  bbob_dart: ^0.1.1
  material_design_icons_flutter: 3.2.3895
  font_awesome_flutter: ^8.4.0
  cached_network_image: ^2.0.0
  numberpicker: ^1.0.0
  sticky_headers: ^0.1.8
  timeago: ^2.0.29
  package_info: ^0.4.0+4
  flutter_slidable: ^0.5.3
  flutter_inappwebview: ^4.0.0+4
  flutter_advanced_networkimage:
    git: https://github.com/antonio02/flutter_advanced_networkimage #To Fix flutter_svg dependency issue!
  url_launcher: ^5.5.0
  flutter_dotenv: ^2.0.1
  tweet_ui: ^2.2.0+3
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  chewie_audio: ^1.0.0+1
  permission_handler: ^5.0.1+1
  gallery_saver: ^2.0.3
  image_picker: ^0.6.7+4
  device_info: ^0.4.2+4
  matrix4_transform: ^1.1.4
  share: '>=0.6.5+4 <2.0.0'
  mime: ^0.9.7
  uni_links: ^0.4.0
  shared_preferences: ^0.5.12+4
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  json_serializable: ^3.2.5
  hive_generator: ^0.7.1
  build_runner: ^1.10.1
  flutter_launcher_icons: "^0.7.3"
  flutter_local_notifications: ^3.0.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/icon.png"
  adaptive_icon_background: "icons/android_bg.png"
  adaptive_icon_foreground: "icons/android_fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/.env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
